corner-radius = 7;
rounded-corners-exclude = [
  "class_g = 'Polybar'"
];

shadow = false;

blur-method = "dual_kawase";
blur-strength = 10;
blur-background-exclude = [
  "class_g = 'slop'",
  "_GTK_FRAME_EXTENTS@",
];

blur-background = true;
blur-background-frame = true;

opacity-rule = [
  "80:class_g = 'kitty'",
  "80:class_g = 'code'",
  "80:class_g    = 'Polybar'",
  "50:class_g    = 'Rofi'"
];

focus-exclude = [ "class_g = 'slop'" ];
fade-exclude  = [ "class_g = 'slop'" ];


backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
log-level = "info";

wintypes:
{
  normal        = { fade = false; shadow = false; };
  tooltip       = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock          = { shadow = false; };
  dnd           = { shadow = false; };
  popup_menu    = { opacity = 0.8; };
  dropdown_menu = { opacity = 0.8; };
};