#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          0
# bspc config focused_border_color \#5E81AC
# bspc config normal_border_color \#5E81AC
bspc config window_gap            15
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#bspc rule -a 'kitty' state=floating rectangle=600x360+0+0 center=true
#bspc rule -a 'Code' state=fullscreen desktop='^2' follow=on

xsetroot -cursor_name left_ptr
xset -dpms s off

## autostart ##
picom &
nitrogen --restore &
prime-offload &
# bash ~/.config/polybar/launch.sh
