[global/wm]
margin-bottom = 0
margin-top = 1

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/main]
;monitor = LVDS-1
bottom = false
fixed-center = true

wm-restack = bspwm

height = 35
offset-y = 15
offset-x = 15

background = ${color.nord-polar-1}
foreground = ${color.nord-snow-2}
radius = 20
pseudo-transparency = false


locale = ja_JP.UTF-8

# [bar/left]
# inherit = bar/main
# font-0 = "Font Awesome 5 Free Regular:size=8;3"
# font-1 = "Font Awesome 5 Free Solid:size=8;3"
# width = 13%
# modules-center = workspaces

# [bar/right]
# inherit = bar/main
# font-0 = "Plus Jakarta Sans Medium:size=11;2"
# font-1 = "Noto Sans CJK JP:size=10;3"
# width = 15%
# offset-x = 85%
# modules-center = date

[bar/center]
inherit = bar/main
font-0 = "Plus Jakarta Sans Medium:size=10;2"
font-1 = "Noto Sans CJK JP:size=10;3"
font-2 = "Noto Serif Tibetan:size=10;3"
width = 180
offset-x = 50%:-90
offset-y = 10
bottom = false
modules-left = time
modules-center = title
modules-right = date
padding-left = 10
padding-right = 10