[module/date]
type = internal/date
interval = 1.0

date = "%A"

format = <label>
format-prefix = 
format-prefix-padding = 1

label = %date%
label-padding = 1
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/time]
type = internal/date
interval = 1.0

time = "%H:%M"

format = <label>
format-prefix = 
format-prefix-padding = 1

label = %time%
label-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
[module/title]
type = custom/text

content = "࿇"
content-foreground = ${color.foreground-alt}
content-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/workspaces]
type = internal/xworkspaces

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; Create click handler used to focus desktop
; Default: true
enable-click = true

; Create scroll handlers used to cycle desktops
; Default: true
enable-scroll = true

; icon-[0-9]+ = <desktop-name>;<icon>
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktops using:
; $ xprop -root _NET_DESKTOP_NAMES
icon-0 = I;
icon-1 = II;
icon-2 = III;
icon-3 = IV;
icon-4 = V;
;icon-default = 

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(active|urgent|occupied|empty)>
; Default: <label-state>
format = <label-state>
format-overline = ${color.background}
format-underline = ${color.background}

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-active = %icon%
label-active-foreground = ${color.nord-frost-1}
;label-active-background = ${color.primary}

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-occupied = %icon%
label-occupied-foreground = ${color.nord-aurora-3}
;label-occupied-background = ${color.gray}

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-urgent = %icon%
label-urgent-foreground = ${color.foreground}
label-urgent-background = ${color.red}

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-empty = %icon%
label-empty-foreground = ${color.nord-aurora-1}
;label-empty-background = ${color.nord-snow-1}

label-active-padding = 3
label-urgent-padding = 3
label-occupied-padding = 3 
label-empty-padding = 3
